sudo: required
language: csharp
dist: xenial
dotnet: 3.1
mono: none

env:
- CONFIGURATION=Release
- CONFIGURATION=Debug

script:
  - dotnet restore
  - dotnet build --configuration $CONFIGURATION
  - dotnet test --configuration $CONFIGURATION
