version: '1.0.2.{build}'

configuration:
- Release

image:
- Visual Studio 2019

platform: Any CPU

init:
- ps: $Env:LABEL = $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\
  COVERALLS_REPO_TOKEN:
    secure: mDGMIHjBciwzuld3r0bezSh7+x6Y6bK7H849/5xerzdfI9AvihkTZV2d8PBQRArC

before_build:
- dotnet --info
- appveyor-retry dotnet restore -v Minimal  

build_script:
- dotnet build -c %CONFIGURATION%

test_script:
- dotnet test --no-build
- bash build/coverage.sh

artifacts:
- path: src\NotMicrosoft.Configuration\bin\Release\*.nupkg

cache:
- '%USERPROFILE%\.nuget\packages'